# Generated by tools/nightly_manifest.py in aurelienpierreeng/ansel -- do not edit.
cask "ansel-nightly" do
  on_arm do
    version "0.0.0+5117.g4e7fd541ce"
    sha256 "97b2578ea428f5127e1a70940a1d7a0ae30960a5a0722cb06f54d07deb078f5c"
    url "https://github.com/aurelienpierreeng/ansel/releases/download/nightly-2026-09/Ansel-0.0.0%2B5117.g4e7fd541ce-arm64.dmg",
        verified: "github.com/aurelienpierreeng/ansel/"
  end
  on_intel do
    version "0.0.0+5117.g4e7fd541ce"
    sha256 "8bfe082a7618196cc4e5cb630b3439072daacce3ee387cf75a3e93b318c2f755"
    url "https://github.com/aurelienpierreeng/ansel/releases/download/nightly-2026-09/Ansel-0.0.0%2B5117.g4e7fd541ce-i386.dmg",
        verified: "github.com/aurelienpierreeng/ansel/"
  end

  name "Ansel (nightly)"
  desc "Photo editor and library manager for digital negatives, nightly build"
  homepage "https://ansel.photos/"

  livecheck do
    url "https://ansel.photos/nightly.json"
    strategy :json do |json|
      json.dig("formats", "dmg-arm64", "version")
    end
  end

  # Nightly builds are not signed or notarized: Gatekeeper quarantines them, and the
  # first launch needs a right-click > Open. See doc/nightly-distribution.md.
  app "Ansel.app"

  zap trash: [
    "~/.config/ansel",
    "~/.cache/ansel",
  ]
end
