# Generated by tools/nightly_manifest.py in aurelienpierreeng/ansel -- do not edit.
cask "ansel-nightly" do
  on_arm do
    version "0.0.0+4845.g0c200c248f"
    sha256 "859f25ff364fa638de77bda6d4f276cbc838475c7c2632a71c37256d19f02d80"
    url "https://github.com/aurelienpierreeng/ansel/releases/download/nightly-2026-08/Ansel-0.0.0%2B4845.g0c200c248f-arm64.dmg",
        verified: "github.com/aurelienpierreeng/ansel/"
  end
  on_intel do
    version "0.0.0+4845.g0c200c248f"
    sha256 "58c881f18922faca1906aab4629d517efc0b0904b1160c0fe1c5493f0b78ed9e"
    url "https://github.com/aurelienpierreeng/ansel/releases/download/nightly-2026-08/Ansel-0.0.0%2B4845.g0c200c248f-i386.dmg",
        verified: "github.com/aurelienpierreeng/ansel/"
  end

  name "Ansel (nightly)"
  desc "Photo editor and library manager for digital negatives, nightly build"
  homepage "https://ansel.photos/"

  livecheck do
    url "https://ansel.photos/nightly.json"
    strategy :json do |json|
      json.dig("formats", "dmg-arm64", "version")
    end
  end

  # Nightly builds are not signed or notarized: Gatekeeper quarantines them, and the
  # first launch needs a right-click > Open. See doc/nightly-distribution.md.
  app "Ansel.app"

  zap trash: [
    "~/.config/ansel",
    "~/.cache/ansel",
  ]
end
