# Generated by tools/nightly_manifest.py in aurelienpierreeng/ansel -- do not edit.
cask "ansel-nightly" do
  on_arm do
    version "0.0.0+4868.ge7aa154f5f"
    sha256 "825c135b744683e44572ac0fe1f31efc4c34a30e1f489f44d66a67f92b25b944"
    url "https://github.com/aurelienpierreeng/ansel/releases/download/nightly-2026-09/Ansel-0.0.0%2B4868.ge7aa154f5f-arm64.dmg",
        verified: "github.com/aurelienpierreeng/ansel/"
  end
  on_intel do
    version "0.0.0+4868.ge7aa154f5f"
    sha256 "a5b0444798c0182168ec7705f99b6c452d79c53921c2decd8488678916e0b302"
    url "https://github.com/aurelienpierreeng/ansel/releases/download/nightly-2026-09/Ansel-0.0.0%2B4868.ge7aa154f5f-i386.dmg",
        verified: "github.com/aurelienpierreeng/ansel/"
  end

  name "Ansel (nightly)"
  desc "Photo editor and library manager for digital negatives, nightly build"
  homepage "https://ansel.photos/"

  livecheck do
    url "https://ansel.photos/nightly.json"
    strategy :json do |json|
      json.dig("formats", "dmg-arm64", "version")
    end
  end

  # Nightly builds are not signed or notarized: Gatekeeper quarantines them, and the
  # first launch needs a right-click > Open. See doc/nightly-distribution.md.
  app "Ansel.app"

  zap trash: [
    "~/.config/ansel",
    "~/.cache/ansel",
  ]
end
